export const siteConfig = {
  name: "AGENTRA LABS",
  shortName: "AGENTRA",
  description:
    "Open-source tools that give AI agents persistent memory, visual understanding, code intelligence, cryptographic identity, temporal reasoning, policy governance, structured communication, strategic planning, cognitive reasoning, and existential grounding. AgenticMemory, AgenticVision, AgenticCodebase, AgenticIdentity, AgenticTime, AgenticContract, AgenticComm, AgenticPlanning, AgenticCognition, and AgenticReality work with any MCP-compatible client.",
  url: "https://www.agentralabs.tech",
  locale: "en_US",
  xHandle: "@agentralab",
  contactEmail: "contact@agentralabs.tech",
  githubOrgUrl: "https://github.com/agentralabs",
  githubWebUrl: "https://github.com/agentralabs/agentralabs-tech-web",
  keywords: [
    "agentic memory",
    "agentic vision",
    "agentic codebase",
    "agentic identity",
    "agenticmemory",
    "agenticvision",
    "agenticcodebase",
    "agenticidentity",
    "agent identity",
    "cryptographic agent identity",
    "mcp tools",
    "model context protocol",
    "ai agent infrastructure",
    "semantic code intelligence",
    "persistent agent memory",
    "long horizon agent memory",
    "ai memory retention",
    "web cartography",
    "visual ai debugging",
    "ai code risk analysis",
    "agentic time",
    "agentictime",
    "temporal reasoning",
    ".atime",
    "deadline tracking",
    "schedule management",
    "temporal decay",
    "agentic contract",
    "agenticcontract",
    "agentic comm",
    "agenticcomm",
    "policy engine",
    "agent communication",
    ".acomm",
    "agent governance",
    ".acon",
    "agentic planning",
    "agenticplanning",
    "strategic planning",
    ".aplan",
    "agent goals",
    "agent decisions",
    "agentic cognition",
    "agenticcognition",
    "cognitive reasoning",
    ".acog",
    "agent cognition",
    "agentic reality",
    "agenticreality",
    "agentic-reality",
    "existential grounding",
    ".areal",
    "deployment consciousness",
    "resource awareness",
    "reality physics",
    "agentic forge",
    "agenticforge",
    "agentic-forge",
    "blueprint engine",
    ".forge",
    "agentic aegis",
    "agenticaegis",
    "agentic-aegis",
    "streaming shield",
    ".aegis",
    "agentic veritas",
    "agenticveritas",
    "agentic-veritas",
    "truth engine",
    ".veritas",
    "agentic evolve",
    "agenticevolve",
    "agentic-evolve",
    "pattern library",
    ".evolve",
    "agent engineering",
    "open source ai",
    "rust ai tooling",
  ],
}

export const navRoutes = [
  { path: "/", priority: 1.0, changeFrequency: "daily" as const },
  { path: "/projects", priority: 0.9, changeFrequency: "daily" as const },
  { path: "/publications", priority: 0.8, changeFrequency: "weekly" as const },
  { path: "/releases", priority: 0.8, changeFrequency: "daily" as const },
  { path: "/docs", priority: 0.8, changeFrequency: "weekly" as const },
  { path: "/feedback", priority: 0.7, changeFrequency: "weekly" as const },
  { path: "/showcase", priority: 0.7, changeFrequency: "weekly" as const },
  { path: "/integrations", priority: 0.7, changeFrequency: "weekly" as const },
  { path: "/blog", priority: 0.6, changeFrequency: "weekly" as const },
  { path: "/partners", priority: 0.6, changeFrequency: "monthly" as const },
]
