export const siteConfig = {
  name: "AGENTRA LABS",
  shortName: "AGENTRA",
  description:
    "Open-source agentic systems lab building AgenticMemory, AgenticVision, and AgenticCodebase for persistent memory, web-scale vision, and semantic code intelligence.",
  url: "https://www.agentralabs.tech",
  locale: "en_US",
  xHandle: "@agentralab",
  contactEmail: "contact@agentralabs.tech",
  githubOrgUrl: "https://github.com/agentralabs",
  githubWebUrl: "https://github.com/agentralabs/agentralabs-tech-web",
  keywords: [
    "agentic memory",
    "agentic vision",
    "agentic codebase",
    "agenticmemory",
    "agenticvision",
    "agenticcodebase",
    "mcp tools",
    "model context protocol",
    "ai agent infrastructure",
    "semantic code intelligence",
    "persistent agent memory",
    "long horizon agent memory",
    "ai memory retention",
    "web cartography",
    "visual ai debugging",
    "ai code risk analysis",
    "agent engineering",
    "open source ai",
    "rust ai tooling",
  ],
}

export const navRoutes = [
  { path: "/", priority: 1.0, changeFrequency: "daily" as const },
  { path: "/projects", priority: 0.9, changeFrequency: "daily" as const },
  { path: "/publications", priority: 0.8, changeFrequency: "weekly" as const },
  { path: "/docs", priority: 0.8, changeFrequency: "weekly" as const },
  { path: "/feedback", priority: 0.7, changeFrequency: "weekly" as const },
  { path: "/showcase", priority: 0.7, changeFrequency: "weekly" as const },
  { path: "/integrations", priority: 0.7, changeFrequency: "weekly" as const },
  { path: "/blog", priority: 0.6, changeFrequency: "weekly" as const },
  { path: "/partners", priority: 0.6, changeFrequency: "monthly" as const },
]
