export type SubstrateTier = "flagship" | "core" | "standard" | "utility"

export interface SubstrateProject {
  key: string
  name: string
  artifact: string
  toolCount: string
  repo: string
  tier: SubstrateTier
  oneLiner: string
}

export const SUBSTRATE_PROJECTS: SubstrateProject[] = [
  {
    key: "agentic-memory",
    name: "AgenticMemory",
    artifact: ".amem",
    toolCount: "147",
    repo: "https://github.com/agentralabs/agentic-memory",
    tier: "flagship",
    oneLiner: "Persistent cognitive graph memory for cross-session reasoning continuity.",
  },
  {
    key: "agentic-vision",
    name: "AgenticVision",
    artifact: ".avis",
    toolCount: "104",
    repo: "https://github.com/agentralabs/agentic-vision",
    tier: "core",
    oneLiner: "Web cartography, browserless mapping, and persistent visual memory.",
  },
  {
    key: "agentic-codebase",
    name: "AgenticCodebase",
    artifact: ".acb",
    toolCount: "73",
    repo: "https://github.com/agentralabs/agentic-codebase",
    tier: "core",
    oneLiner: "Semantic code intelligence with impact analysis and breakage prediction.",
  },
  {
    key: "agentic-identity",
    name: "AgenticIdentity",
    artifact: ".aid",
    toolCount: "42",
    repo: "https://github.com/agentralabs/agentic-identity",
    tier: "core",
    oneLiner: "Cryptographic agent identity with Ed25519 anchors and signed receipts.",
  },
  {
    key: "agentic-time",
    name: "AgenticTime",
    artifact: ".atime",
    toolCount: "19",
    repo: "https://github.com/agentralabs/agentic-time",
    tier: "standard",
    oneLiner: "Temporal reasoning with deadlines, schedules, and decay models.",
  },
  {
    key: "agentic-contract",
    name: "AgenticContract",
    artifact: ".acon",
    toolCount: "38",
    repo: "https://github.com/agentralabs/agentic-contract",
    tier: "standard",
    oneLiner: "Policy governance with risk limits, approval workflows, and self-healing.",
  },
  {
    key: "agentic-comm",
    name: "AgenticComm",
    artifact: ".acomm",
    toolCount: "17",
    repo: "https://github.com/agentralabs/agentic-comm",
    tier: "standard",
    oneLiner: "Structured inter-agent communication with channels and subscriptions.",
  },
  {
    key: "agentic-planning",
    name: "AgenticPlanning",
    artifact: ".aplan",
    toolCount: "13",
    repo: "https://github.com/agentralabs/agentic-planning",
    tier: "standard",
    oneLiner: "Persistent goals, decisions, commitments, and strategic reasoning.",
  },
  {
    key: "agentic-cognition",
    name: "AgenticCognition",
    artifact: ".acog",
    toolCount: "24",
    repo: "https://github.com/agentralabs/agentic-cognition",
    tier: "standard",
    oneLiner: "Longitudinal user modeling with belief physics and decision fingerprints.",
  },
  {
    key: "agentic-reality",
    name: "AgenticReality",
    artifact: ".areal",
    toolCount: "15",
    repo: "https://github.com/agentralabs/agentic-reality",
    tier: "standard",
    oneLiner: "Deployment consciousness, resource awareness, and reality physics.",
  },
  {
    key: "agentic-veritas",
    name: "AgenticVeritas",
    artifact: ".averitas",
    toolCount: "10",
    repo: "https://github.com/agentralabs/agentic-veritas",
    tier: "standard",
    oneLiner: "Intent compilation, uncertainty detection, and truth verification.",
  },
  {
    key: "agentic-data",
    name: "AgenticData",
    artifact: ".adat",
    toolCount: "\u2014",
    repo: "https://github.com/agentralabs/agentic-data",
    tier: "standard",
    oneLiner: "Schemas, lineage, anomalies, and data provenance.",
  },
  {
    key: "agentic-workflow",
    name: "AgenticWorkflow",
    artifact: ".awf",
    toolCount: "\u2014",
    repo: "https://github.com/agentralabs/agentic-workflow",
    tier: "standard",
    oneLiner: "Durable workflow state, recovery, and approval gates.",
  },
  {
    key: "agentic-connect",
    name: "AgenticConnect",
    artifact: ".acnx",
    toolCount: "\u2014",
    repo: "https://github.com/agentralabs/agentic-connect",
    tier: "standard",
    oneLiner: "Resilient and observable API integrations.",
  },
  {
    key: "agentic-forge",
    name: "agentic-forge",
    artifact: "\u2014",
    toolCount: "15",
    repo: "https://github.com/agentralabs/agentic-forge",
    tier: "utility",
    oneLiner: "Blueprint engine with dependency resolution.",
  },
  {
    key: "agentic-aegis",
    name: "agentic-aegis",
    artifact: "\u2014",
    toolCount: "\u2014",
    repo: "https://github.com/agentralabs/agentic-aegis",
    tier: "utility",
    oneLiner: "Streaming validation and shadow execution.",
  },
  {
    key: "agentic-evolve",
    name: "agentic-evolve",
    artifact: "\u2014",
    toolCount: "\u2014",
    repo: "https://github.com/agentralabs/agentic-evolve",
    tier: "utility",
    oneLiner: "Pattern library and collective crystallization.",
  },
  {
    key: "agentic-sdk",
    name: "agentic-sdk",
    artifact: "\u2014",
    toolCount: "\u2014",
    repo: "https://github.com/agentralabs/agentic-sdk",
    tier: "utility",
    oneLiner: "Shared traits and contracts across the substrate.",
  },
]
